apiVersion: v1
kind: Pod
metadata:
  labels:
    run: poderror
  name: poderror
  namespace: demo
spec:
  volumes:
  - name: nginx-index-file
    configMap:
      name: index-html
  containers:
  - image: npinx
    name: podwitherror
    volumeMounts:
    - name: nginx-index
      mountPath: /usr/share/nginx/html/