apiVersion: v1
kind: Service
metadata:
  labels:
    run: deploymissconfig
  name: deploymissconfig-svc
  namespace: demo
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080  
  selector:
    app: nnging